/* eslint-disable @typescript-eslint/no-unsafe-assignment */

import Head from "next/head";
import { PropsWithChildren } from "react";

// Components
import NavBar from "../Home/NavBar";
import SideBar from "../Home/SideBar";

const Page = (props: PropsWithChildren) =>
{

  return (
    <div className="font-inter flex flex-col overflow-y-auto h-screen bg-slate-100">
      <Head>
        <title>Truffles Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="flex flex-1">
        <SideBar />
        <div className="flex-1">
          { props.children }
        </div>
      </div>
    </div>
  );
};

export default Page;
